const PAINT_COLORS = [
    { code: '#FFFFFF', name: 'Trắng Tinh Khiết', category: 'white' },
    { code: '#FFFAFA', name: 'Trắng Tuyết', category: 'white' },
    { code: '#F0FFF0', name: 'Trắng Mật Ong', category: 'white' },
    { code: '#F5FFFA', name: 'Trắng Bạc Hà', category: 'white' },
    { code: '#F0FFFF', name: 'Trắng Azure', category: 'white' },
    { code: '#F0F8FF', name: 'Trắng Alice Blue', category: 'white' },
    { code: '#FFF5EE', name: 'Trắng Vỏ Sò', category: 'white' },
    { code: '#F5F5F5', name: 'Trắng Khói', category: 'white' },
    { code: '#FFFFF0', name: 'Trắng Ngà', category: 'white' },
    { code: '#FFFAF0', name: 'Trắng Hoa Huệ', category: 'white' },
    { code: '#FAF0E6', name: 'Trắng Lanh', category: 'white' },
    { code: '#FDF5E6', name: 'Trắng Cổ Điển', category: 'white' },
    { code: '#FAEBD7', name: 'Trắng Cổ Xưa', category: 'white' },
    { code: '#FFEFD5', name: 'Vàng Kem Nhạt', category: 'white' },
    { code: '#FFEBCD', name: 'Vàng Blanched Almond', category: 'white' },

    { code: '#F5F5DC', name: 'Kem Ngọc Trai', category: 'yellow' },
    { code: '#FFF8DC', name: 'Vàng Ngô', category: 'yellow' },
    { code: '#FFE4B5', name: 'Vàng Hạnh Nhân', category: 'yellow' },
    { code: '#FFDEAD', name: 'Vàng Cát', category: 'yellow' },
    { code: '#F0E68C', name: 'Vàng Khaki', category: 'yellow' },
    { code: '#FFD700', name: 'Vàng Vàng', category: 'yellow' },
    { code: '#FFA500', name: 'Vàng Cam', category: 'orange' },
    { code: '#FFFF00', name: 'Vàng Thuần', category: 'yellow' },
    { code: '#FFFFE0', name: 'Vàng Nhạt', category: 'yellow' },
    { code: '#FFFACD', name: 'Vàng Chanh Nhạt', category: 'yellow' },
    { code: '#FAFAD2', name: 'Vàng Goldenrod Nhạt', category: 'yellow' },
    { code: '#EEE8AA', name: 'Vàng Goldenrod Xám', category: 'yellow' },
    { code: '#F0E130', name: 'Vàng Lemon', category: 'yellow' },
    { code: '#BDB76B', name: 'Vàng Khaki Tối', category: 'yellow' },
    { code: '#DAA520', name: 'Vàng Goldenrod', category: 'yellow' },

    { code: '#B8860B', name: 'Vàng Goldenrod Tối', category: 'brown' },
    { code: '#E6D7C3', name: 'Be Nhạt', category: 'brown' },
    { code: '#D2B48C', name: 'Nâu Tan', category: 'brown' },
    { code: '#DEB887', name: 'Nâu Gỗ Sồi', category: 'brown' },
    { code: '#BC8F8F', name: 'Nâu Hồng', category: 'brown' },
    { code: '#CD853F', name: 'Nâu Peru', category: 'brown' },
    { code: '#D2691E', name: 'Nâu Chocolate', category: 'brown' },
    { code: '#8B7355', name: 'Nâu Đất', category: 'brown' },
    { code: '#A0522D', name: 'Nâu Sienna', category: 'brown' },
    { code: '#8B4513', name: 'Nâu Yên', category: 'brown' },
    { code: '#654321', name: 'Nâu Sẫm', category: 'brown' },
    { code: '#704214', name: 'Nâu Sepia', category: 'brown' },
    { code: '#5C4033', name: 'Nâu Gỗ', category: 'brown' },
    { code: '#8B4726', name: 'Nâu Đỏ', category: 'brown' },
    { code: '#A0785A', name: 'Nâu Camel', category: 'brown' },

    { code: '#FFB6C1', name: 'Hồng Nhạt', category: 'pink' },
    { code: '#FFC0CB', name: 'Hồng Phấn', category: 'pink' },
    { code: '#FFE4E1', name: 'Hồng Misty Rose', category: 'pink' },
    { code: '#FADADD', name: 'Hồng Lavender Blush', category: 'pink' },
    { code: '#FFF0F5', name: 'Hồng Lavender Blush Nhạt', category: 'pink' },
    { code: '#FFB0C4', name: 'Hồng Light Pink', category: 'pink' },
    { code: '#FF69B4', name: 'Hồng Hot Pink', category: 'pink' },
    { code: '#FF1493', name: 'Hồng Deep Pink', category: 'pink' },
    { code: '#DB7093', name: 'Hồng Pale Violet', category: 'pink' },
    { code: '#C71585', name: 'Hồng Đỏ Medium Violet', category: 'pink' },
    { code: '#FF6F91', name: 'Hồng Carnation', category: 'pink' },
    { code: '#FF85A1', name: 'Hồng Salmon', category: 'pink' },
    { code: '#FFAEC9', name: 'Hồng Bubble Gum', category: 'pink' },
    { code: '#F88379', name: 'Hồng Coral', category: 'pink' },
    { code: '#E75480', name: 'Hồng Đào', category: 'pink' },

    { code: '#E6E6FA', name: 'Tím Lavender', category: 'purple' },
    { code: '#D8BFD8', name: 'Tím Thistle', category: 'purple' },
    { code: '#DDA0DD', name: 'Tím Mận', category: 'purple' },
    { code: '#EE82EE', name: 'Tím Violet', category: 'purple' },
    { code: '#DA70D6', name: 'Tím Orchid', category: 'purple' },
    { code: '#FF00FF', name: 'Tím Magenta', category: 'purple' },
    { code: '#BA55D3', name: 'Tím Orchid Medium', category: 'purple' },
    { code: '#9370DB', name: 'Tím Medium Purple', category: 'purple' },
    { code: '#8A2BE2', name: 'Tím Blue Violet', category: 'purple' },
    { code: '#9400D3', name: 'Tím Dark Violet', category: 'purple' },
    { code: '#9932CC', name: 'Tím Dark Orchid', category: 'purple' },
    { code: '#8B008B', name: 'Tím Dark Magenta', category: 'purple' },
    { code: '#800080', name: 'Tím Purple', category: 'purple' },
    { code: '#4B0082', name: 'Tím Chàm', category: 'purple' },
    { code: '#6A0DAD', name: 'Tím Hoàng Gia', category: 'purple' },

    { code: '#663399', name: 'Tím Rebecca Purple', category: 'purple' },
    { code: '#5D3FD3', name: 'Tím Iris', category: 'purple' },
    { code: '#7B68EE', name: 'Tím Slate Blue Medium', category: 'purple' },
    { code: '#6A5ACD', name: 'Tím Slate Blue', category: 'purple' },
    { code: '#483D8B', name: 'Tím Slate Blue Tối', category: 'purple' },
    { code: '#E0FFFF', name: 'Xanh Cyan Nhạt', category: 'blue' },
    { code: '#AFEEEE', name: 'Xanh Pale Turquoise', category: 'blue' },
    { code: '#7FFFD4', name: 'Xanh Aquamarine', category: 'blue' },
    { code: '#40E0D0', name: 'Xanh Turquoise', category: 'blue' },
    { code: '#48D1CC', name: 'Xanh Medium Turquoise', category: 'blue' },

    { code: '#00CED1', name: 'Xanh Dark Turquoise', category: 'blue' },
    { code: '#00FFFF', name: 'Xanh Cyan', category: 'blue' },
    { code: '#00BFFF', name: 'Xanh Deep Sky Blue', category: 'blue' },
    { code: '#87CEEB', name: 'Xanh Sky Blue', category: 'blue' },
    { code: '#87CEFA', name: 'Xanh Light Sky Blue', category: 'blue' },
    { code: '#B0E0E6', name: 'Xanh Powder Blue', category: 'blue' },
    { code: '#ADD8E6', name: 'Xanh Light Blue', category: 'blue' },
    { code: '#5F9EA0', name: 'Xanh Cadet Blue', category: 'blue' },
    { code: '#4682B4', name: 'Xanh Steel Blue', category: 'blue' },
    { code: '#6495ED', name: 'Xanh Cornflower Blue', category: 'blue' },

    { code: '#1E90FF', name: 'Xanh Dodger Blue', category: 'blue' },
    { code: '#4169E1', name: 'Xanh Royal Blue', category: 'blue' },
    { code: '#0000FF', name: 'Xanh Blue', category: 'blue' },
    { code: '#0000CD', name: 'Xanh Medium Blue', category: 'blue' },
    { code: '#00008B', name: 'Xanh Dark Blue', category: 'blue' },
    { code: '#000080', name: 'Xanh Navy', category: 'blue' },
    { code: '#191970', name: 'Xanh Midnight Blue', category: 'blue' },
    { code: '#1560BD', name: 'Xanh Denim', category: 'blue' },
    { code: '#003153', name: 'Xanh Prussian', category: 'blue' },
    { code: '#0047AB', name: 'Xanh Cobalt', category: 'blue' },

    { code: '#98FB98', name: 'Xanh Pale Green', category: 'green' },
    { code: '#90EE90', name: 'Xanh Light Green', category: 'green' },
    { code: '#00FF7F', name: 'Xanh Spring Green', category: 'green' },
    { code: '#00FA9A', name: 'Xanh Medium Spring Green', category: 'green' },
    { code: '#7FFF00', name: 'Xanh Chartreuse', category: 'green' },
    { code: '#7CFC00', name: 'Xanh Lawn Green', category: 'green' },
    { code: '#00FF00', name: 'Xanh Lime', category: 'green' },
    { code: '#32CD32', name: 'Xanh Lime Green', category: 'green' },
    { code: '#9ACD32', name: 'Xanh Yellow Green', category: 'green' },
    { code: '#ADFF2F', name: 'Xanh Green Yellow', category: 'green' },

    { code: '#3CB371', name: 'Xanh Medium Sea Green', category: 'green' },
    { code: '#2E8B57', name: 'Xanh Sea Green', category: 'green' },
    { code: '#228B22', name: 'Xanh Forest Green', category: 'green' },
    { code: '#008000', name: 'Xanh Green', category: 'green' },
    { code: '#006400', name: 'Xanh Dark Green', category: 'green' },
    { code: '#66CDAA', name: 'Xanh Medium Aquamarine', category: 'green' },
    { code: '#8FBC8F', name: 'Xanh Dark Sea Green', category: 'green' },
    { code: '#20B2AA', name: 'Xanh Light Sea Green', category: 'green' },
    { code: '#008B8B', name: 'Xanh Dark Cyan', category: 'green' },
    { code: '#008080', name: 'Xanh Teal', category: 'green' },

    { code: '#556B2F', name: 'Xanh Dark Olive Green', category: 'green' },
    { code: '#6B8E23', name: 'Xanh Olive Drab', category: 'green' },
    { code: '#808000', name: 'Xanh Olive', category: 'green' },
    { code: '#8B864E', name: 'Xanh Khaki Dark', category: 'green' },
    { code: '#9DC183', name: 'Xanh Pistachio', category: 'green' },
    { code: '#50C878', name: 'Xanh Emerald', category: 'green' },
    { code: '#00A86B', name: 'Xanh Jade', category: 'green' },
    { code: '#29AB87', name: 'Xanh Jungle', category: 'green' },
    { code: '#4CBB17', name: 'Xanh Kelly', category: 'green' },
    { code: '#0BDA51', name: 'Xanh Malachite', category: 'green' },

    { code: '#FFA07A', name: 'Cam Salmon Nhạt', category: 'orange' },
    { code: '#FA8072', name: 'Cam Salmon', category: 'orange' },
    { code: '#E9967A', name: 'Cam Dark Salmon', category: 'orange' },
    { code: '#F08080', name: 'Cam Light Coral', category: 'orange' },
    { code: '#FF7F50', name: 'Cam Coral', category: 'orange' },
    { code: '#FF6347', name: 'Cam Tomato', category: 'orange' },
    { code: '#FF8C00', name: 'Cam Dark Orange', category: 'orange' },
    { code: '#FF4500', name: 'Cam Orange Red', category: 'orange' },
    { code: '#FFA500', name: 'Cam Orange', category: 'orange' },
    { code: '#FFB347', name: 'Cam Pastel', category: 'orange' },

    { code: '#FFDAB9', name: 'Cam Peach Puff', category: 'orange' },
    { code: '#FFAB91', name: 'Cam Deep Peach', category: 'orange' },
    { code: '#FF8066', name: 'Cam Burnt Orange', category: 'orange' },
    { code: '#CC5500', name: 'Cam Rust', category: 'orange' },
    { code: '#FF7518', name: 'Cam Pumpkin', category: 'orange' },
    { code: '#DC143C', name: 'Đỏ Crimson', category: 'red' },
    { code: '#FF0000', name: 'Đỏ Red', category: 'red' },
    { code: '#B22222', name: 'Đỏ Firebrick', category: 'red' },
    { code: '#8B0000', name: 'Đỏ Dark Red', category: 'red' },
    { code: '#800000', name: 'Đỏ Maroon', category: 'red' },

    { code: '#CD5C5C', name: 'Đỏ Indian Red', category: 'red' },
    { code: '#F08080', name: 'Đỏ Light Coral', category: 'red' },
    { code: '#FF6961', name: 'Đỏ Pastel Red', category: 'red' },
    { code: '#FF2400', name: 'Đỏ Scarlet', category: 'red' },
    { code: '#C41E3A', name: 'Đỏ Cardinal', category: 'red' },
    { code: '#E34234', name: 'Đỏ Vermilion', category: 'red' },
    { code: '#AA0000', name: 'Đỏ Blood Red', category: 'red' },
    { code: '#880808', name: 'Đỏ Oxblood', category: 'red' },
    { code: '#722F37', name: 'Đỏ Wine', category: 'red' },
    { code: '#A52A2A', name: 'Đỏ Brown', category: 'red' },

    { code: '#D3D3D3', name: 'Xám Light Gray', category: 'gray' },
    { code: '#DCDCDC', name: 'Xám Gainsboro', category: 'gray' },
    { code: '#C0C0C0', name: 'Xám Silver', category: 'gray' },
    { code: '#A9A9A9', name: 'Xám Dark Gray', category: 'gray' },
    { code: '#808080', name: 'Xám Gray', category: 'gray' },
    { code: '#696969', name: 'Xám Dim Gray', category: 'gray' },
    { code: '#778899', name: 'Xám Light Slate', category: 'gray' },
    { code: '#708090', name: 'Xám Slate', category: 'gray' },
    { code: '#2F4F4F', name: 'Xám Dark Slate', category: 'gray' },
    { code: '#36454F', name: 'Xám Charcoal', category: 'gray' },

    { code: '#000000', name: 'Đen Black', category: 'gray' },
    { code: '#0A0A0A', name: 'Đen Jet', category: 'gray' },
    { code: '#1C1C1C', name: 'Đen Eerie', category: 'gray' },
    { code: '#3B3C3D', name: 'Xám Onyx', category: 'gray' },
    { code: '#71797E', name: 'Xám Nickel', category: 'gray' },
    { code: '#E5E4E2', name: 'Xám Platinum', category: 'gray' },
    { code: '#BCC6CC', name: 'Xám Silver Sand', category: 'gray' },
    { code: '#848884', name: 'Xám Battleship', category: 'gray' },
    { code: '#B2BEB5', name: 'Xám Ash', category: 'gray' },
    { code: '#87CEEB', name: 'Xám Blue', category: 'gray' },

    { code: '#FFE4C4', name: 'Kem Bisque', category: 'white' },
    { code: '#FFEBCD', name: 'Kem Blanched Almond', category: 'white' },
    { code: '#FFEFD5', name: 'Kem Papaya Whip', category: 'white' },
    { code: '#FFE4B5', name: 'Kem Moccasin', category: 'white' },
    { code: '#FFDAB9', name: 'Kem Peach Puff', category: 'orange' },
    { code: '#EEE8AA', name: 'Kem Pale Goldenrod', category: 'yellow' },
    { code: '#F5DEB3', name: 'Kem Wheat', category: 'yellow' },
    { code: '#FFF8DC', name: 'Kem Cornsilk', category: 'yellow' },
    { code: '#FFFACD', name: 'Kem Lemon Chiffon', category: 'yellow' },
    { code: '#FFFFE0', name: 'Kem Light Yellow', category: 'yellow' },

    { code: '#8B4789', name: 'Tím Plum', category: 'purple' },
    { code: '#702963', name: 'Tím Byzantium', category: 'purple' },
    { code: '#8806CE', name: 'Tím Vivid', category: 'purple' },
    { code: '#6F2DA8', name: 'Tím Grape', category: 'purple' },
    { code: '#5A4FCF', name: 'Tím Iris', category: 'purple' },
    { code: '#5D3FD3', name: 'Tím Neon', category: 'purple' },
    { code: '#9B59B6', name: 'Tím Amethyst', category: 'purple' },
    { code: '#8E44AD', name: 'Tím Wisteria', category: 'purple' },
    { code: '#9C27B0', name: 'Tím Purple Material', category: 'purple' },
    { code: '#AB47BC', name: 'Tím Light Purple', category: 'purple' },

    { code: '#CE93D8', name: 'Tím Lilac', category: 'purple' },
    { code: '#E1BEE7', name: 'Tím Mauve', category: 'purple' },
    { code: '#F3E5F5', name: 'Tím Lavender Blush', category: 'purple' },
    { code: '#DDA0DD', name: 'Tím Plum Light', category: 'purple' },
    { code: '#C8A2C8', name: 'Tím Lilac Medium', category: 'purple' },
    { code: '#FF55A3', name: 'Hồng Magenta Rose', category: 'pink' },
    { code: '#FE6F5E', name: 'Hồng Bittersweet', category: 'pink' },
    { code: '#FF5470', name: 'Hồng Fiery Rose', category: 'pink' },
    { code: '#F653A6', name: 'Hồng Fuchsia', category: 'pink' },
    { code: '#FD3F92', name: 'Hồng Brilliant Rose', category: 'pink' },

    { code: '#FBAED2', name: 'Hồng Lavender Rose', category: 'pink' },
    { code: '#F7B2BD', name: 'Hồng Pink Lace', category: 'pink' },
    { code: '#EE5A6F', name: 'Hồng Cerise', category: 'pink' },
    { code: '#D15070', name: 'Hồng Blush', category: 'pink' },
    { code: '#DE5D83', name: 'Hồng Cranberry', category: 'pink' },
    { code: '#FCE5CD', name: 'Be Champagne', category: 'brown' },
    { code: '#E8D5B7', name: 'Be Camel', category: 'brown' },
    { code: '#C9B88E', name: 'Be Khaki', category: 'brown' },
    { code: '#C4A57B', name: 'Be Tan', category: 'brown' },
    { code: '#C19A6B', name: 'Be Camel Dark', category: 'brown' },

    { code: '#B8956A', name: 'Be Sand', category: 'brown' },
    { code: '#966F33', name: 'Be Sienna', category: 'brown' },
    { code: '#755C48', name: 'Be Coffee', category: 'brown' },
    { code: '#704241', name: 'Nâu Tuscany', category: 'brown' },
    { code: '#6F4E37', name: 'Nâu Coffee Bean', category: 'brown' },
    { code: '#3B2219', name: 'Nâu Bistre', category: 'brown' },
    { code: '#321414', name: 'Nâu Seal', category: 'brown' },
    { code: '#3D2B1F', name: 'Nâu Dark Lava', category: 'brown' },
    { code: '#483C32', name: 'Nâu Taupe', category: 'brown' },
    { code: '#964B00', name: 'Nâu Orange Brown', category: 'brown' },

    { code: '#954535', name: 'Nâu Chestnut', category: 'brown' },
    { code: '#7B3F00', name: 'Nâu Chocolate Dark', category: 'brown' },
    { code: '#825736', name: 'Nâu Copper', category: 'brown' },
    { code: '#80461B', name: 'Nâu Russet', category: 'brown' },
    { code: '#592720', name: 'Nâu Auburn', category: 'brown' },
    { code: '#00FFFF', name: 'Xanh Aqua', category: 'blue' },
    { code: '#7DF9FF', name: 'Xanh Electric Blue', category: 'blue' },
    { code: '#01C3D1', name: 'Xanh Vivid Sky Blue', category: 'blue' },
    { code: '#009DC4', name: 'Xanh Cerulean', category: 'blue' },
    { code: '#0077BE', name: 'Xanh Ocean Blue', category: 'blue' },

    { code: '#006994', name: 'Xanh Sea Blue', category: 'blue' },
    { code: '#003F5C', name: 'Xanh Deep Sea', category: 'blue' },
    { code: '#00394E', name: 'Xanh Dark Slate Blue', category: 'blue' },
    { code: '#002F3B', name: 'Xanh Midnight Navy', category: 'blue' },
    { code: '#0C2340', name: 'Xanh Oxford Blue', category: 'blue' },
    { code: '#98D8E8', name: 'Xanh Powder', category: 'blue' },
    { code: '#A4D8E1', name: 'Xanh Columbia Blue', category: 'blue' },
    { code: '#B9D9EB', name: 'Xanh Light Pastel Blue', category: 'blue' },
    { code: '#BFEFFF', name: 'Xanh Ice Blue', category: 'blue' },
    { code: '#A0E4F1', name: 'Xanh Baby Blue', category: 'blue' },

    { code: '#81D8D0', name: 'Xanh Tiffany Blue', category: 'blue' },
    { code: '#76D7EA', name: 'Xanh Sky Blue Light', category: 'blue' },
    { code: '#5DADE2', name: 'Xanh Picton Blue', category: 'blue' },
    { code: '#3498DB', name: 'Xanh Peter River', category: 'blue' },
    { code: '#2E86C1', name: 'Xanh Belize Hole', category: 'blue' },
    { code: '#21618C', name: 'Xanh Dark Blue Grey', category: 'blue' },
    { code: '#1B4F72', name: 'Xanh Midnight', category: 'blue' },
    { code: '#154360', name: 'Xanh Dark Cerulean', category: 'blue' },
    { code: '#0B3D59', name: 'Xanh Dark Blue Navy', category: 'blue' },
    { code: '#0E6BA8', name: 'Xanh True Blue', category: 'blue' },

    { code: '#3944BC', name: 'Xanh Persian Blue', category: 'blue' },
    { code: '#002FA7', name: 'Xanh International Klein', category: 'blue' },
    { code: '#003DA5', name: 'Xanh Royal Blue Dark', category: 'blue' },
    { code: '#004AAD', name: 'Xanh Dark Powder Blue', category: 'blue' },
    { code: '#0057B7', name: 'Xanh Blue NCS', category: 'blue' },
    { code: '#26619C', name: 'Xanh Lapis Lazuli', category: 'blue' },
    { code: '#0D52BD', name: 'Xanh Bright Navy', category: 'blue' },
    { code: '#084C9E', name: 'Xanh True Blue Dark', category: 'blue' },
    { code: '#004F98', name: 'Xanh Honolulu', category: 'blue' },
    { code: '#00509D', name: 'Xanh St Patrick', category: 'blue' },

    { code: '#A2F5BF', name: 'Xanh Lá Mint', category: 'green' },
    { code: '#93E9BE', name: 'Xanh Lá Sea Foam', category: 'green' },
    { code: '#7FE5B3', name: 'Xanh Lá Foam', category: 'green' },
    { code: '#6CD4A7', name: 'Xanh Lá Shamrock', category: 'green' },
    { code: '#5FC99D', name: 'Xanh Lá Eucalyptus', category: 'green' },
    { code: '#48C9B0', name: 'Xanh Lá Medium Turquoise', category: 'green' },
    { code: '#45B39D', name: 'Xanh Lá Puerto Rico', category: 'green' },
    { code: '#36B386', name: 'Xanh Lá Mountain Meadow', category: 'green' },
    { code: '#27AE60', name: 'Xanh Lá Nephritis', category: 'green' },
    { code: '#229954', name: 'Xanh Lá Green Haze', category: 'green' },

    { code: '#1E8449', name: 'Xanh Lá Salem', category: 'green' },
    { code: '#186A3B', name: 'Xanh Lá Jewel', category: 'green' },
    { code: '#145A32', name: 'Xanh Lá Japanese Laurel', category: 'green' },
    { code: '#0E4B26', name: 'Xanh Lá British Racing', category: 'green' },
    { code: '#0B5345', name: 'Xanh Lá Sherwood', category: 'green' },
    { code: '#ACF0BA', name: 'Xanh Lá Celadon', category: 'green' },
    { code: '#8EE6A6', name: 'Xanh Lá Light Green', category: 'green' },
    { code: '#82E0AA', name: 'Xanh Lá Light Sea Green', category: 'green' },
    { code: '#76D7C4', name: 'Xanh Lá Pearl Aqua', category: 'green' },
    { code: '#73C6B6', name: 'Xanh Lá Monte Carlo', category: 'green' },

    { code: '#58D68D', name: 'Xanh Lá Emerald Light', category: 'green' },
    { code: '#52BE80', name: 'Xanh Lá Ocean Green', category: 'green' },
    { code: '#3DCC70', name: 'Xanh Lá UFO Green', category: 'green' },
    { code: '#2ECC71', name: 'Xanh Lá Emerald', category: 'green' },
    { code: '#28B463', name: 'Xanh Lá Dark Pastel Green', category: 'green' },
    { code: '#239B56', name: 'Xanh Lá Amazon', category: 'green' },
    { code: '#1D8348', name: 'Xanh Lá Fun Green', category: 'green' },
    { code: '#17A589', name: 'Xanh Lá Light Sea Green', category: 'green' },
    { code: '#138D75', name: 'Xanh Lá Jungle Green', category: 'green' },
    { code: '#117A65', name: 'Xanh Lá Observatory', category: 'green' },

    { code: '#0F6F5B', name: 'Xanh Lá Pine Green', category: 'green' },
    { code: '#0D5E4F', name: 'Xanh Lá Deep Sea Green', category: 'green' },
    { code: '#0B5244', name: 'Xanh Lá Tropical Rain Forest', category: 'green' },
    { code: '#A4DE02', name: 'Xanh Lá Android Green', category: 'green' },
    { code: '#76FF03', name: 'Xanh Lá Bright Green', category: 'green' },
    { code: '#64DD17', name: 'Xanh Lá Lime Green Vivid', category: 'green' },
    { code: '#00E676', name: 'Xanh Lá Spring Green', category: 'green' },
    { code: '#00C853', name: 'Xanh Lá Dark Pastel', category: 'green' },
    { code: '#1B5E20', name: 'Xanh Lá Forest Green Dark', category: 'green' },
    { code: '#2E7D32', name: 'Xanh Lá Dark Green', category: 'green' },

    { code: '#388E3C', name: 'Xanh Lá Green', category: 'green' },
    { code: '#43A047', name: 'Xanh Lá Medium Green', category: 'green' },
    { code: '#4CAF50', name: 'Xanh Lá Material Green', category: 'green' },
    { code: '#66BB6A', name: 'Xanh Lá Medium Light Green', category: 'green' },
    { code: '#81C784', name: 'Xanh Lá Light Emerald', category: 'green' },
    { code: '#A5D6A7', name: 'Xanh Lá Granny Smith Apple', category: 'green' },
    { code: '#C8E6C9', name: 'Xanh Lá Tea Green', category: 'green' },
    { code: '#E8F5E9', name: 'Xanh Lá Honeydew', category: 'green' },
    { code: '#F1F8E9', name: 'Xanh Lá Nyanza', category: 'green' },
    { code: '#558B2F', name: 'Xanh Lá Olive Green', category: 'green' },

    { code: '#689F38', name: 'Xanh Lá Olive Light', category: 'green' },
    { code: '#7CB342', name: 'Xanh Lá Apple', category: 'green' },
    { code: '#8BC34A', name: 'Xanh Lá Yellow Green', category: 'green' },
    { code: '#9CCC65', name: 'Xanh Lá Light Lime', category: 'green' },
    { code: '#AED581', name: 'Xanh Lá Pistachio', category: 'green' },
    { code: '#C5E1A5', name: 'Xanh Lá Pale Olive', category: 'green' },
    { code: '#DCEDC8', name: 'Xanh Lá Pale Spring Bud', category: 'green' },
    { code: '#F1F8E9', name: 'Xanh Lá Pale Nyanza', category: 'green' },
    { code: '#827717', name: 'Xanh Lá Olive Drab', category: 'green' },
    { code: '#9E9D24', name: 'Xanh Lá Citron', category: 'green' },

    { code: '#AFB42B', name: 'Xanh Lá Lemon Curry', category: 'green' },
    { code: '#C0CA33', name: 'Xanh Lá Lime Material', category: 'green' },
    { code: '#D4E157', name: 'Xanh Lá Yellow Green Crayola', category: 'green' },
    { code: '#DCE775', name: 'Xanh Lá Greenery', category: 'green' },
    { code: '#E6EE9C', name: 'Xanh Lá Key Lime', category: 'green' },
    { code: '#F0F4C3', name: 'Xanh Lá Tea Green Light', category: 'green' },
    { code: '#F9FBE7', name: 'Xanh Lá Cream', category: 'green' },
    { code: '#FFCC80', name: 'Cam Peach', category: 'orange' },
    { code: '#FFB74D', name: 'Cam Gold', category: 'orange' },
    { code: '#FFA726', name: 'Cam Mango', category: 'orange' },

    { code: '#FF9800', name: 'Cam Material Orange', category: 'orange' },
    { code: '#FB8C00', name: 'Cam Dark', category: 'orange' },
    { code: '#F57C00', name: 'Cam Dark Tangerine', category: 'orange' },
    { code: '#EF6C00', name: 'Cam International', category: 'orange' },
    { code: '#E65100', name: 'Cam Dark Pumpkin', category: 'orange' },
    { code: '#FF6F00', name: 'Cam Amber', category: 'orange' },
    { code: '#FF8F00', name: 'Cam Amber Dark', category: 'orange' },
    { code: '#FFA000', name: 'Cam Amber Light', category: 'orange' },
    { code: '#FFB300', name: 'Cam Selective Yellow', category: 'orange' },
    { code: '#FFC107', name: 'Cam Material Amber', category: 'orange' },
    { code: '#FFCA28', name: 'Cam Saffron', category: 'orange' },

    { code: '#FFD54F', name: 'Cam Mustard', category: 'orange' },
    { code: '#FFE082', name: 'Cam Jasmine', category: 'orange' },
    { code: '#FFECB3', name: 'Cam Cream', category: 'orange' },
    { code: '#FFF8E1', name: 'Cam Lemon Chiffon', category: 'orange' },
    { code: '#FFFDE7', name: 'Cam Cream Light', category: 'orange' },
    { code: '#FF5722', name: 'Cam Deep Orange', category: 'orange' },
    { code: '#F4511E', name: 'Cam Vermilion', category: 'orange' },
    { code: '#E64A19', name: 'Cam Flame', category: 'orange' },
    { code: '#D84315', name: 'Cam Burnt Sienna', category: 'orange' },
    { code: '#BF360C', name: 'Cam Mahogany', category: 'orange' },

    { code: '#FF7043', name: 'Cam Coral Medium', category: 'orange' },
    { code: '#FF8A65', name: 'Cam Salmon Light', category: 'orange' },
    { code: '#FFAB91', name: 'Cam Vivid Tangerine', category: 'orange' },
    { code: '#FFCCBC', name: 'Cam Peach Light', category: 'orange' },
    { code: '#FBE9E7', name: 'Cam Misty Rose', category: 'orange' },
    { code: '#FFF3E0', name: 'Cam Papaya Whip', category: 'orange' },
    { code: '#D32F2F', name: 'Đỏ Red Material', category: 'red' },
    { code: '#C62828', name: 'Đỏ Red Dark', category: 'red' },
    { code: '#B71C1C', name: 'Đỏ Red Darker', category: 'red' },
    { code: '#EF5350', name: 'Đỏ Sunset Orange', category: 'red' },

    { code: '#E53935', name: 'Đỏ Red Medium', category: 'red' },
    { code: '#F44336', name: 'Đỏ Red Primary', category: 'red' },
    { code: '#EF5350', name: 'Đỏ Red Light', category: 'red' },
    { code: '#E57373', name: 'Đỏ Light Coral Red', category: 'red' },
    { code: '#EF9A9A', name: 'Đỏ Pastel Red', category: 'red' },
    { code: '#FFCDD2', name: 'Đỏ Misty Rose', category: 'red' },
    { code: '#FFEBEE', name: 'Đỏ Snow', category: 'red' },
    { code: '#AD1457', name: 'Đỏ Ruby', category: 'red' },
    { code: '#C2185B', name: 'Đỏ Pink Red', category: 'red' },
    { code: '#D81B60', name: 'Đỏ Persian Rose', category: 'red' },

    { code: '#E91E63', name: 'Đỏ Pink Material', category: 'red' },
    { code: '#EC407A', name: 'Đỏ Hot Pink Light', category: 'red' },
    { code: '#F06292', name: 'Đỏ Cyclamen', category: 'red' },
    { code: '#F48FB1', name: 'Đỏ Pink Light', category: 'red' },
    { code: '#F8BBD0', name: 'Đỏ Cameo Pink', category: 'red' },
    { code: '#FCE4EC', name: 'Đỏ Lavender Blush', category: 'red' },
    { code: '#880E4F', name: 'Đỏ Burgundy', category: 'red' },
    { code: '#991B1B', name: 'Đỏ Crimson Dark', category: 'red' },
    { code: '#7F1D1D', name: 'Đỏ Carmine', category: 'red' },
    { code: '#450A0A', name: 'Đỏ Rosewood', category: 'red' },

    { code: '#ECEFF1', name: 'Xám Blue Grey 50', category: 'gray' },
    { code: '#CFD8DC', name: 'Xám Blue Grey 100', category: 'gray' },
    { code: '#B0BEC5', name: 'Xám Blue Grey 200', category: 'gray' },
    { code: '#90A4AE', name: 'Xám Blue Grey 300', category: 'gray' },
    { code: '#78909C', name: 'Xám Blue Grey 400', category: 'gray' },
    { code: '#607D8B', name: 'Xám Blue Grey 500', category: 'gray' },
    { code: '#546E7A', name: 'Xám Blue Grey 600', category: 'gray' },
    { code: '#455A64', name: 'Xám Blue Grey 700', category: 'gray' },
    { code: '#37474F', name: 'Xám Blue Grey 800', category: 'gray' },
    { code: '#263238', name: 'Xám Blue Grey 900', category: 'gray' },

    { code: '#FAFAFA', name: 'Xám 50', category: 'gray' },
    { code: '#F5F5F5', name: 'Xám 100', category: 'gray' },
    { code: '#EEEEEE', name: 'Xám 200', category: 'gray' },
    { code: '#E0E0E0', name: 'Xám 300', category: 'gray' },
    { code: '#BDBDBD', name: 'Xám 400', category: 'gray' },
    { code: '#9E9E9E', name: 'Xám 500', category: 'gray' },
    { code: '#757575', name: 'Xám 600', category: 'gray' },
    { code: '#616161', name: 'Xám 700', category: 'gray' },
    { code: '#424242', name: 'Xám 800', category: 'gray' },
    { code: '#212121', name: 'Xám 900', category: 'gray' },

    { code: '#EFEBE9', name: 'Nâu 50', category: 'brown' },
    { code: '#D7CCC8', name: 'Nâu 100', category: 'brown' },
    { code: '#BCAAA4', name: 'Nâu 200', category: 'brown' },
    { code: '#A1887F', name: 'Nâu 300', category: 'brown' },
    { code: '#8D6E63', name: 'Nâu 400', category: 'brown' },
    { code: '#795548', name: 'Nâu 500', category: 'brown' },
    { code: '#6D4C41', name: 'Nâu 600', category: 'brown' },
    { code: '#5D4037', name: 'Nâu 700', category: 'brown' },
    { code: '#4E342E', name: 'Nâu 800', category: 'brown' },
    { code: '#3E2723', name: 'Nâu 900', category: 'brown' },

    { code: '#B0E57C', name: 'Xanh Lá Spring Bud', category: 'green' },
    { code: '#D4E157', name: 'Xanh Lá Pear', category: 'green' },
    { code: '#CDDC39', name: 'Xanh Lá Lime Material', category: 'green' },
    { code: '#C0CA33', name: 'Xanh Lá Rio Grande', category: 'green' },
    { code: '#AFB42B', name: 'Xanh Lá Olive Yellow', category: 'green' },
    { code: '#9E9D24', name: 'Xanh Lá Olive Drab', category: 'green' },
    { code: '#827717', name: 'Xanh Lá Pesto', category: 'green' },
    { code: '#F0F4C3', name: 'Xanh Lá Pale Lime', category: 'green' },
    { code: '#E6EE9C', name: 'Xanh Lá Key Lime Pie', category: 'green' },
    { code: '#DCE775', name: 'Xanh Lá Light Lime', category: 'green' },

    { code: '#F9FBE7', name: 'Xanh Lá Cream Light', category: 'green' },
    { code: '#FF80AB', name: 'Hồng Pink A100', category: 'pink' },
    { code: '#FF4081', name: 'Hồng Pink A200', category: 'pink' },
    { code: '#F50057', name: 'Hồng Pink A400', category: 'pink' },
    { code: '#C51162', name: 'Hồng Pink A700', category: 'pink' },
    { code: '#EA80FC', name: 'Tím Purple A100', category: 'purple' },
    { code: '#E040FB', name: 'Tím Purple A200', category: 'purple' },
    { code: '#D500F9', name: 'Tím Purple A400', category: 'purple' },
    { code: '#AA00FF', name: 'Tím Purple A700', category: 'purple' },
    { code: '#B388FF', name: 'Tím Deep Purple A100', category: 'purple' },

    { code: '#7C4DFF', name: 'Tím Deep Purple A200', category: 'purple' },
    { code: '#651FFF', name: 'Tím Deep Purple A400', category: 'purple' },
    { code: '#6200EA', name: 'Tím Deep Purple A700', category: 'purple' },
    { code: '#8C9EFF', name: 'Xanh Indigo A100', category: 'blue' },
    { code: '#536DFE', name: 'Xanh Indigo A200', category: 'blue' },
    { code: '#3D5AFE', name: 'Xanh Indigo A400', category: 'blue' },
    { code: '#304FFE', name: 'Xanh Indigo A700', category: 'blue' },
    { code: '#82B1FF', name: 'Xanh Blue A100', category: 'blue' },
    { code: '#448AFF', name: 'Xanh Blue A200', category: 'blue' },
    { code: '#2979FF', name: 'Xanh Blue A400', category: 'blue' },

    { code: '#2962FF', name: 'Xanh Blue A700', category: 'blue' },
    { code: '#80D8FF', name: 'Xanh Light Blue A100', category: 'blue' },
    { code: '#40C4FF', name: 'Xanh Light Blue A200', category: 'blue' },
    { code: '#00B0FF', name: 'Xanh Light Blue A400', category: 'blue' },
    { code: '#0091EA', name: 'Xanh Light Blue A700', category: 'blue' },
    { code: '#84FFFF', name: 'Xanh Cyan A100', category: 'blue' },
    { code: '#18FFFF', name: 'Xanh Cyan A200', category: 'blue' },
    { code: '#00E5FF', name: 'Xanh Cyan A400', category: 'blue' },
    { code: '#00B8D4', name: 'Xanh Cyan A700', category: 'blue' },
    { code: '#A7FFEB', name: 'Xanh Teal A100', category: 'green' },

    { code: '#64FFDA', name: 'Xanh Teal A200', category: 'green' },
    { code: '#1DE9B6', name: 'Xanh Teal A400', category: 'green' },
    { code: '#00BFA5', name: 'Xanh Teal A700', category: 'green' },
    { code: '#B9F6CA', name: 'Xanh Green A100', category: 'green' },
    { code: '#69F0AE', name: 'Xanh Green A200', category: 'green' },
    { code: '#00E676', name: 'Xanh Green A400', category: 'green' },
    { code: '#00C853', name: 'Xanh Green A700', category: 'green' },
    { code: '#CCFF90', name: 'Xanh Light Green A100', category: 'green' },
    { code: '#B2FF59', name: 'Xanh Light Green A200', category: 'green' },
    { code: '#76FF03', name: 'Xanh Light Green A400', category: 'green' },

    { code: '#64DD17', name: 'Xanh Light Green A700', category: 'green' },
    { code: '#F4FF81', name: 'Vàng Lime A100', category: 'yellow' },
    { code: '#EEFF41', name: 'Vàng Lime A200', category: 'yellow' },
    { code: '#C6FF00', name: 'Vàng Lime A400', category: 'yellow' },
    { code: '#AEEA00', name: 'Vàng Lime A700', category: 'yellow' },
    { code: '#FFFF8D', name: 'Vàng Yellow A100', category: 'yellow' },
    { code: '#FFFF00', name: 'Vàng Yellow A200', category: 'yellow' },
    { code: '#FFEA00', name: 'Vàng Yellow A400', category: 'yellow' },
    { code: '#FFD600', name: 'Vàng Yellow A700', category: 'yellow' },
    { code: '#FFE57F', name: 'Cam Amber A100', category: 'orange' },

    { code: '#FFD740', name: 'Cam Amber A200', category: 'orange' },
    { code: '#FFC400', name: 'Cam Amber A400', category: 'orange' },
    { code: '#FFAB00', name: 'Cam Amber A700', category: 'orange' },
    { code: '#FFD180', name: 'Cam Orange A100', category: 'orange' },
    { code: '#FFAB40', name: 'Cam Orange A200', category: 'orange' },
    { code: '#FF9100', name: 'Cam Orange A400', category: 'orange' },
    { code: '#FF6D00', name: 'Cam Orange A700', category: 'orange' },
    { code: '#FF9E80', name: 'Cam Deep Orange A100', category: 'orange' },
    { code: '#FF6E40', name: 'Cam Deep Orange A200', category: 'orange' },
    { code: '#FF3D00', name: 'Cam Deep Orange A400', category: 'orange' },

    { code: '#DD2C00', name: 'Cam Deep Orange A700', category: 'orange' },
    { code: '#FF8A80', name: 'Đỏ Red A100', category: 'red' },
    { code: '#FF5252', name: 'Đỏ Red A200', category: 'red' },
    { code: '#FF1744', name: 'Đỏ Red A400', category: 'red' },
    { code: '#D50000', name: 'Đỏ Red A700', category: 'red' },
    { code: '#311B92', name: 'Tím Deep Purple 900', category: 'purple' },
    { code: '#4A148C', name: 'Tím Purple 900', category: 'purple' },
    { code: '#1A237E', name: 'Xanh Indigo 900', category: 'blue' },
    { code: '#0D47A1', name: 'Xanh Blue 900', category: 'blue' },
    { code: '#01579B', name: 'Xanh Light Blue 900', category: 'blue' },

    { code: '#006064', name: 'Xanh Cyan 900', category: 'blue' },
    { code: '#004D40', name: 'Xanh Teal 900', category: 'green' },
    { code: '#1B5E20', name: 'Xanh Green 900', category: 'green' },
    { code: '#33691E', name: 'Xanh Light Green 900', category: 'green' },
    { code: '#827717', name: 'Xanh Lime 900', category: 'green' },
    { code: '#F57F17', name: 'Vàng Yellow 900', category: 'yellow' },
    { code: '#FF6F00', name: 'Cam Amber 900', category: 'orange' },
    { code: '#E65100', name: 'Cam Orange 900', category: 'orange' },
    { code: '#BF360C', name: 'Cam Deep Orange 900', category: 'orange' },
    { code: '#880E4F', name: 'Đỏ Pink 900', category: 'red' },

    { code: '#B71C1C', name: 'Đỏ Red 900', category: 'red' },
    { code: '#3E2723', name: 'Nâu Brown 900', category: 'brown' },
    { code: '#263238', name: 'Xám Blue Grey 900', category: 'gray' },
    { code: '#212121', name: 'Xám Grey 900', category: 'gray' },
    { code: '#00695C', name: 'Xanh Teal 800', category: 'green' },
    { code: '#00796B', name: 'Xanh Teal 700', category: 'green' },
    { code: '#00897B', name: 'Xanh Teal 600', category: 'green' },
    { code: '#009688', name: 'Xanh Teal 500', category: 'green' },
    { code: '#26A69A', name: 'Xanh Teal 400', category: 'green' },
    { code: '#4DB6AC', name: 'Xanh Teal 300', category: 'green' },

    { code: '#80CBC4', name: 'Xanh Teal 200', category: 'green' },
    { code: '#B2DFDB', name: 'Xanh Teal 100', category: 'green' },
    { code: '#E0F2F1', name: 'Xanh Teal 50', category: 'green' },
    { code: '#1565C0', name: 'Xanh Blue 800', category: 'blue' },
    { code: '#1976D2', name: 'Xanh Blue 700', category: 'blue' },
    { code: '#1E88E5', name: 'Xanh Blue 600', category: 'blue' },
    { code: '#2196F3', name: 'Xanh Blue 500', category: 'blue' },
    { code: '#42A5F5', name: 'Xanh Blue 400', category: 'blue' },
    { code: '#64B5F6', name: 'Xanh Blue 300', category: 'blue' },
    { code: '#90CAF9', name: 'Xanh Blue 200', category: 'blue' },

    { code: '#BBDEFB', name: 'Xanh Blue 100', category: 'blue' },
    { code: '#E3F2FD', name: 'Xanh Blue 50', category: 'blue' },
    { code: '#283593', name: 'Xanh Indigo 800', category: 'blue' },
    { code: '#303F9F', name: 'Xanh Indigo 700', category: 'blue' },
    { code: '#3949AB', name: 'Xanh Indigo 600', category: 'blue' },
    { code: '#3F51B5', name: 'Xanh Indigo 500', category: 'blue' },
    { code: '#5C6BC0', name: 'Xanh Indigo 400', category: 'blue' },
    { code: '#7986CB', name: 'Xanh Indigo 300', category: 'blue' },
    { code: '#9FA8DA', name: 'Xanh Indigo 200', category: 'blue' },
    { code: '#C5CAE9', name: 'Xanh Indigo 100', category: 'blue' },

    { code: '#E8EAF6', name: 'Xanh Indigo 50', category: 'blue' },
    { code: '#4527A0', name: 'Tím Deep Purple 800', category: 'purple' },
    { code: '#512DA8', name: 'Tím Deep Purple 700', category: 'purple' },
    { code: '#5E35B1', name: 'Tím Deep Purple 600', category: 'purple' },
    { code: '#673AB7', name: 'Tím Deep Purple 500', category: 'purple' },
    { code: '#7E57C2', name: 'Tím Deep Purple 400', category: 'purple' },
    { code: '#9575CD', name: 'Tím Deep Purple 300', category: 'purple' },
    { code: '#B39DDB', name: 'Tím Deep Purple 200', category: 'purple' },
    { code: '#D1C4E9', name: 'Tím Deep Purple 100', category: 'purple' },
    { code: '#EDE7F6', name: 'Tím Deep Purple 50', category: 'purple' },

    { code: '#6A1B9A', name: 'Tím Purple 800', category: 'purple' },
    { code: '#7B1FA2', name: 'Tím Purple 700', category: 'purple' },
    { code: '#8E24AA', name: 'Tím Purple 600', category: 'purple' },
    { code: '#9C27B0', name: 'Tím Purple 500', category: 'purple' },
    { code: '#AB47BC', name: 'Tím Purple 400', category: 'purple' },
    { code: '#BA68C8', name: 'Tím Purple 300', category: 'purple' },
    { code: '#CE93D8', name: 'Tím Purple 200', category: 'purple' },
    { code: '#E1BEE7', name: 'Tím Purple 100', category: 'purple' },
    { code: '#F3E5F5', name: 'Tím Purple 50', category: 'purple' },
    { code: '#AD1457', name: 'Hồng Pink 800', category: 'pink' },

    { code: '#C2185B', name: 'Hồng Pink 700', category: 'pink' },
    { code: '#D81B60', name: 'Hồng Pink 600', category: 'pink' },
    { code: '#E91E63', name: 'Hồng Pink 500', category: 'pink' },
    { code: '#EC407A', name: 'Hồng Pink 400', category: 'pink' },
    { code: '#F06292', name: 'Hồng Pink 300', category: 'pink' },
    { code: '#F48FB1', name: 'Hồng Pink 200', category: 'pink' },
    { code: '#F8BBD0', name: 'Hồng Pink 100', category: 'pink' },
    { code: '#FCE4EC', name: 'Hồng Pink 50', category: 'pink' },
    { code: '#01579B', name: 'Xanh Light Blue 800', category: 'blue' },
    { code: '#0277BD', name: 'Xanh Light Blue 700', category: 'blue' },

    { code: '#0288D1', name: 'Xanh Light Blue 600', category: 'blue' },
    { code: '#03A9F4', name: 'Xanh Light Blue 500', category: 'blue' },
    { code: '#29B6F6', name: 'Xanh Light Blue 400', category: 'blue' },
    { code: '#4FC3F7', name: 'Xanh Light Blue 300', category: 'blue' },
    { code: '#81D4FA', name: 'Xanh Light Blue 200', category: 'blue' },
    { code: '#B3E5FC', name: 'Xanh Light Blue 100', category: 'blue' },
    { code: '#E1F5FE', name: 'Xanh Light Blue 50', category: 'blue' },
    { code: '#006064', name: 'Xanh Cyan 800', category: 'blue' },
    { code: '#00838F', name: 'Xanh Cyan 700', category: 'blue' },
    { code: '#0097A7', name: 'Xanh Cyan 600', category: 'blue' },

    { code: '#00ACC1', name: 'Xanh Cyan 500', category: 'blue' },
    { code: '#26C6DA', name: 'Xanh Cyan 400', category: 'blue' },
    { code: '#4DD0E1', name: 'Xanh Cyan 300', category: 'blue' },
    { code: '#80DEEA', name: 'Xanh Cyan 200', category: 'blue' },
    { code: '#B2EBF2', name: 'Xanh Cyan 100', category: 'blue' },
    { code: '#E0F7FA', name: 'Xanh Cyan 50', category: 'blue' },
    { code: '#1B5E20', name: 'Xanh Green 800', category: 'green' },
    { code: '#2E7D32', name: 'Xanh Green 700', category: 'green' },
    { code: '#388E3C', name: 'Xanh Green 600', category: 'green' },
    { code: '#4CAF50', name: 'Xanh Green 500', category: 'green' },

    { code: '#66BB6A', name: 'Xanh Green 400', category: 'green' },
    { code: '#81C784', name: 'Xanh Green 300', category: 'green' },
    { code: '#A5D6A7', name: 'Xanh Green 200', category: 'green' },
    { code: '#C8E6C9', name: 'Xanh Green 100', category: 'green' },
    { code: '#E8F5E9', name: 'Xanh Green 50', category: 'green' },
    { code: '#33691E', name: 'Xanh Light Green 800', category: 'green' },
    { code: '#558B2F', name: 'Xanh Light Green 700', category: 'green' },
    { code: '#689F38', name: 'Xanh Light Green 600', category: 'green' },
    { code: '#7CB342', name: 'Xanh Light Green 500', category: 'green' },
    { code: '#9CCC65', name: 'Xanh Light Green 400', category: 'green' },

    { code: '#AED581', name: 'Xanh Light Green 300', category: 'green' },
    { code: '#C5E1A5', name: 'Xanh Light Green 200', category: 'green' },
    { code: '#DCEDC8', name: 'Xanh Light Green 100', category: 'green' },
    { code: '#F1F8E9', name: 'Xanh Light Green 50', category: 'green' },
    { code: '#827717', name: 'Xanh Lime 800', category: 'green' },
    { code: '#9E9D24', name: 'Xanh Lime 700', category: 'green' },
    { code: '#AFB42B', name: 'Xanh Lime 600', category: 'green' },
    { code: '#CDDC39', name: 'Xanh Lime 500', category: 'green' },
    { code: '#D4E157', name: 'Xanh Lime 400', category: 'green' },
    { code: '#DCE775', name: 'Xanh Lime 300', category: 'green' },

    { code: '#E6EE9C', name: 'Xanh Lime 200', category: 'green' },
    { code: '#F0F4C3', name: 'Xanh Lime 100', category: 'green' },
    { code: '#F9FBE7', name: 'Xanh Lime 50', category: 'green' },
    { code: '#F57F17', name: 'Vàng Yellow 800', category: 'yellow' },
    { code: '#F9A825', name: 'Vàng Yellow 700', category: 'yellow' },
    { code: '#FBC02D', name: 'Vàng Yellow 600', category: 'yellow' },
    { code: '#FFEB3B', name: 'Vàng Yellow 500', category: 'yellow' },
    { code: '#FFEE58', name: 'Vàng Yellow 400', category: 'yellow' },
    { code: '#FFF176', name: 'Vàng Yellow 300', category: 'yellow' },
    { code: '#FFF59D', name: 'Vàng Yellow 200', category: 'yellow' },

    { code: '#FFF9C4', name: 'Vàng Yellow 100', category: 'yellow' },
    { code: '#FFFDE7', name: 'Vàng Yellow 50', category: 'yellow' },
    { code: '#FF6F00', name: 'Cam Amber 800', category: 'orange' },
    { code: '#FF8F00', name: 'Cam Amber 700', category: 'orange' },
    { code: '#FFA000', name: 'Cam Amber 600', category: 'orange' },
    { code: '#FFC107', name: 'Cam Amber 500', category: 'orange' },
    { code: '#FFCA28', name: 'Cam Amber 400', category: 'orange' },
    { code: '#FFD54F', name: 'Cam Amber 300', category: 'orange' },
    { code: '#FFE082', name: 'Cam Amber 200', category: 'orange' },
    { code: '#FFECB3', name: 'Cam Amber 100', category: 'orange' },

    { code: '#FFF8E1', name: 'Cam Amber 50', category: 'orange' },
    { code: '#E65100', name: 'Cam Orange 800', category: 'orange' },
    { code: '#EF6C00', name: 'Cam Orange 700', category: 'orange' },
    { code: '#F57C00', name: 'Cam Orange 600', category: 'orange' },
    { code: '#FF9800', name: 'Cam Orange 500', category: 'orange' },
    { code: '#FFA726', name: 'Cam Orange 400', category: 'orange' },
    { code: '#FFB74D', name: 'Cam Orange 300', category: 'orange' },
    { code: '#FFCC80', name: 'Cam Orange 200', category: 'orange' },
    { code: '#FFE0B2', name: 'Cam Orange 100', category: 'orange' },
    { code: '#FFF3E0', name: 'Cam Orange 50', category: 'orange' },

    { code: '#BF360C', name: 'Cam Deep Orange 800', category: 'orange' },
    { code: '#D84315', name: 'Cam Deep Orange 700', category: 'orange' },
    { code: '#E64A19', name: 'Cam Deep Orange 600', category: 'orange' },
    { code: '#FF5722', name: 'Cam Deep Orange 500', category: 'orange' },
    { code: '#FF7043', name: 'Cam Deep Orange 400', category: 'orange' },
    { code: '#FF8A65', name: 'Cam Deep Orange 300', category: 'orange' },
    { code: '#FFAB91', name: 'Cam Deep Orange 200', category: 'orange' },
    { code: '#FFCCBC', name: 'Cam Deep Orange 100', category: 'orange' },
    { code: '#FBE9E7', name: 'Cam Deep Orange 50', category: 'orange' },
    { code: '#B71C1C', name: 'Đỏ Red 800', category: 'red' },

    { code: '#C62828', name: 'Đỏ Red 700', category: 'red' },
    { code: '#D32F2F', name: 'Đỏ Red 600', category: 'red' },
    { code: '#F44336', name: 'Đỏ Red 500', category: 'red' },
    { code: '#EF5350', name: 'Đỏ Red 400', category: 'red' },
    { code: '#E57373', name: 'Đỏ Red 300', category: 'red' },
    { code: '#EF9A9A', name: 'Đỏ Red 200', category: 'red' },
    { code: '#FFCDD2', name: 'Đỏ Red 100', category: 'red' },
    { code: '#FFEBEE', name: 'Đỏ Red 50', category: 'red' },
    { code: '#3E2723', name: 'Nâu Brown 800', category: 'brown' },
    { code: '#4E342E', name: 'Nâu Brown 700', category: 'brown' },

    { code: '#5D4037', name: 'Nâu Brown 600', category: 'brown' },
    { code: '#6D4C41', name: 'Nâu Brown 400', category: 'brown' },
    { code: '#8D6E63', name: 'Nâu Brown 300', category: 'brown' },
    { code: '#A1887F', name: 'Nâu Brown 200', category: 'brown' },
    { code: '#BCAAA4', name: 'Nâu Brown 100', category: 'brown' },
    { code: '#D7CCC8', name: 'Nâu Brown 50', category: 'brown' },
    { code: '#263238', name: 'Xám Blue Grey 800', category: 'gray' },
    { code: '#37474F', name: 'Xám Blue Grey 700', category: 'gray' },
    { code: '#455A64', name: 'Xám Blue Grey 600', category: 'gray' },
    { code: '#546E7A', name: 'Xám Blue Grey 500', category: 'gray' },

    { code: '#607D8B', name: 'Xám Blue Grey 400', category: 'gray' },
    { code: '#78909C', name: 'Xám Blue Grey 300', category: 'gray' },
    { code: '#90A4AE', name: 'Xám Blue Grey 200', category: 'gray' },
    { code: '#B0BEC5', name: 'Xám Blue Grey 100', category: 'gray' },
    { code: '#CFD8DC', name: 'Xám Blue Grey 50', category: 'gray' },
    { code: '#F8B195', name: 'Cam Peachy Pink', category: 'orange' },
    { code: '#F67280', name: 'Hồng Tulip', category: 'pink' },
    { code: '#C06C84', name: 'Hồng Puce', category: 'pink' },
    { code: '#6C5B7B', name: 'Tím Cyber Grape', category: 'purple' },
    { code: '#355C7D', name: 'Xanh Bdazzled Blue', category: 'blue' }
];

console.log(`Loaded ${PAINT_COLORS.length} paint colors`);